Updated GhActions file

diff --git a/.github/workflows/frontend-actions.yml b/.github/workflows/frontend-actions.yml
--- a/.github/workflows/frontend-actions.yml
+++ b/.github/workflows/frontend-actions.yml
@@ -30,7 +30,7 @@ jobs:
                 ls -R ./URLScraperForm/
             - name: "Copy files to S3 bucket"
               run: | 
-                aws s3 sync ./URLScraperForm/ s3://${{env.BUCKET_NAME}}/ --recursive --exclude ".git*" || echo "Error copying files to s3"
-            - name: "Debug: List files in s3 bucket"
-              run: |
-                aws s3 ls s3://${{env.BUCKET_NAME}}/
+                aws s3 sync ./URLScraperForm/ s3://${{env.BUCKET_NAME}}/ || echo "Error copying files to s3"
+            # - name: "Debug: List files in s3 bucket"
+            #   run: |
+            #     aws s3 ls s3://${{env.BUCKET_NAME}}/
